# Generated by Django 5.2.7 on 2025-11-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_favorito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Racha',
        ),
    ]
